### ISSUE TITLE
[Update] service.subtitles.wizdom

### ISSUE THREAD

**Issue by wizupdate** [xbmc/repo-scripts#1059]
### Add-on details:
- **General**
  - Add-on name: Wizdom Subs
  - Add-on ID: service.subtitles.wizdom
  - Version number: 1.0.7
  - Kodi/repository version: krypton, leia
  - URL: https://github.com/wizupdate/service.subtitles.wizdom
  - Revision/tag: 1.0.7
  - Branch: master

### Description of changes:
Source URL change from the initial release of this add-on.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Rechi** [comment]
Please submit a Pull Request.

**Comment by wizupdate** [comment]
Even if the add-on is already in the repo?

**Comment by Rechi** [comment]
Yes.

**Comment by enen92** [comment]
Closing as it looks stalled. Please let us know if you need us to PR on your behalf and we'll reopen the issue

**Comment by wizupdate** [comment]
Hi
Can you please help with the PR?

**Comment by wizupdate** [comment]
Hey

Thank you for reopening  our issue.
Can you please help us with creating the pull request?

**Comment by wizupdate** [comment]
Hey
Can you please PR on our behalf?

**Comment by enen92** [comment]
Yes will do it today.

**Comment by enen92** [comment]
@wizupdate is the tag still correct? It looks like the last version is already 2.0.2: https://github.com/wizupdate/service.subtitles.wizdom/releases

**Comment by wizupdate** [comment]
Thank you for your help.
The latest release is indeed 2.0.2.

**Comment by enen92** [comment]
PR was made: https://github.com/xbmc/repo-scripts/pull/1263

I'll review the code and likely request a few changes. I'll pick them from your repo (upstream location of the code)

**Comment by enen92** [comment]
@wizupdate see comments in the pull request. Please move the discussion there.

**Comment by wizupdate** [comment]
@enen92 Thank you very much for your help.

**Comment by basrieter** [comment]
Continued here: https://github.com/xbmc/repo-scripts/pull/1263
