### ISSUE TITLE
[Remove] script.artistslideshow-helper

### ISSUE THREAD

**Issue by pkscout** [xbmc/repo-scripts#1203]
### Add-on details:
- **General**
  - Add-on name: Artist Slideshow Helper
  - Add-on ID: script.artistslideshow-helper
  - Version number: 0.4.4
  - Kodi/repository version: Helix

- **Code location**
  - URL: https://github.com/pkscout/script.artistslideshow-helper/
  - Revision/tag: 
  - Branch: master

### Description of changes:
Artist Slideshow Helper is no longer needed and should be removed from all versions of the official Kodi repository.  Artist Slideshow has been updated to either incorporate the features or has changed so that the Helper application is no longer needed (and doesn't work in some cases).

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
@pkscout issue is addressed in https://github.com/xbmc/repo-scripts/pull/1218 and https://github.com/xbmc/repo-scripts/pull/1219 . Can you confirm this issue is for gotham and helix so both can be merged?

**Comment by pkscout** [comment]
Yes, this addresses both #1218 and #1219, so those two issues can be merged.
