### ISSUE TITLE
Update script.module.sseclient - broken version (0.0.24)

### ISSUE THREAD

**Issue by JavaWiz1** [xbmc/repo-scripts#1255]
### Add-on details:
- **General**
Name=sseclient
ID=script.module.sseclient
Kodi/repository version: 0.0.24
https://github.com/xbmc/repo-scripts/tree/leia/script.module.sseclient

- **Code location**
  - URL: https://github.com/xbmc/repo-scripts/tree/leia/script.module.sseclient
  - Revision/tag: 
  - Branch: leia

### Description of changes:
This module is used for the ArloView plugin, and was updated from v0.0.20 to v0.0.24 (on Aug. 27th) which is currently broken.  I did not update this module, not sure why/how it was updated. 
It needs to be **v0.0.20 or v0.0.22**.

**Comment by enen92** [comment]
ping @Rechi

**Comment by enen92** [comment]
Btw @JavaWiz1 ArloView plugin needs to be updated to python3 as it is at the moment broken in matrix

**Comment by JavaWiz1** [comment]
@enen92, yes, looking @ Python3 now.

**Comment by enen92** [comment]
See: https://github.com/xbmc/repo-scripts/pull/1258#issuecomment-572038192
