### ISSUE TITLE
script.module.soupsieve is missing imports and extensions points

### ISSUE THREAD

**Issue by Herrminator** [xbmc/repo-scripts#1943]
### Add-on details:

- Add-on name: Soup Sieve
- Add-on ID: script.module.soupsieve
- Version number: 1.9.6
- Kodi/repository version: Leia

### Ownership
- [ ] I am the owner of this add-on

### Broken because:
The add-on doesn't define its extension point properly, so it cannot be found by BeautifulSoup. The following line is missing in `addon.xml`:
```xml
<extension point="xbmc.python.module" library="lib" />
```
On Leia (Kodi 18.x with Python 2.x), it also lacks the import of a required backport module. This can be fixed by adding this line to the `<requires>` element of `addon.xml`:
```xml
<import addon="script.module.backports.functools_lru_cache" version="1.6.1"/>
```

**Comment by enen92** [comment]
@Gujal00

**Comment by enen92** [comment]
Fixed in the PR above

**Comment by Gujal00** [comment]
Sorry, just saw this. Thanks for fixing @enen92
