### ISSUE TITLE
My addon, OzWeather, is now broken in Kodi 18.9 and below (fine in Kodi 19+)

### ISSUE THREAD

**Issue by bossanova808** [xbmc/repo-scripts#2156]
### Add-on details:
- Add-on name: OzWeather
- Add-on ID: weather.ozweather
- Version number: 1.02
- Kodi/repository version: Leia and below (i.e. <19)

### Ownership
- [x] I am the owner of this add-on

### Broken because:

Complete website change to upstream scraped data source (Weatherzone).  I can't be bothered working on old versions any more (as I don't have any older installations around and just generally not interested in working with Python 2 any more!) - and (not surprisingly) no one else has stepped up to backport the changes from OzWeather V2+ back to Python2.

V2 for Kodi Matrix and above use a completely different data source, and is working fine, and I will continue to support it.

**Comment by razzeee** [comment]
I've put up the needed changes as PRs

**Comment by bossanova808** [comment]
Thank you!  I guess I can close this issue now that those are in place?

**Comment by razzeee** [comment]
Sure, but feel free to subscribe to the PRs
