### ISSUE TITLE
CU LRC Lyrics v6.4.1 broken on XBOX due to ctypes 

### ISSUE THREAD

**Issue by Hawkedon** [xbmc/repo-scripts#2312]
### Add-on details:

- Add-on name: CU LRC Lyrics
- Add-on ID:script.cu.lrclyrics
- Version number:6.4.1
- Kodi/repository version:Matrix

### Ownership
- [ ] I am the owner of this add-on

### Broken because:

Hi @ronie, the latest update v6.4.1 of CU LRC Lyrics add-on uses the ctypes module, which is not supported on XBOX platform due to the platform restriction. The add-on doesn’t work any more due to this.

**Comment by ronie** [comment]
thanx for the report!
should be fixed in 6.5.1

**Comment by Hawkedon** [comment]
Thanks @ronie. It works fine now!
