### ISSUE TITLE
[script.metropolicontools] 0.0.6

### ISSUE THREAD

**Issue by metropolicon** [xbmc/repo-scripts#383]
### Add-on details:

- **General**
  - Add-on name: metropolicontools
  - Add-on ID: script.metropolicontools
  - Version number: 0.0.8
  - Kodi/repository version: Jarvis and Krypton

- **Code location**
  - URL: https://github.com/metropolicon/script.metropolicontools
  - Revision/tag: 
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
Is this to be available for Jarvis and onwards of krypton and onwards? You submitted the same zip for two branches so I assume you want the addon to work with Jarvis and Krypton. Normally you specify the base version for your script and it will work for both that version and the above versions.

Also, please define the addon.xml correctly for your version. So assuming you want this one for Jarvis and above, `xbmc.python` in `addon.xml` should have version 2.24.0 and not 2.13.0 as now.

**Comment by enen92** [comment]
xbmc.addon should also be 	16.0.0 . See here: http://kodi.wiki/view/addon.xml

**Comment by MartijnKaijser** [comment]
It's pointless to have the same Addon version submitted to two different kodi versions. Pick one. 
@ronie can you also do a check on the script?

**Comment by MartijnKaijser** [comment]
Also our main language is English and  other French. So news should be in English. Description and summary is wrong as it doesn't tell anything useful.

**Comment by metropolicon** [comment]
sorry to all... i'm beginner...
your comments help me to make a good request...
please delete those two issues i'll do it again when i adapt it with all your recommandation

thanks

**Comment by ronie** [comment]
see: https://github.com/xbmc/repo-skins/issues/24
