### ISSUE TITLE
[Initial submission] script.musicfinder v1.0.0

### ISSUE THREAD

**Issue by chrisbevan** [xbmc/repo-scripts#453]
### Add-on details:
- **General**
  - Add-on name: Music Finder Script
  - Add-on ID: script.musicfinder
  - Version number: 1.0.0
  - Kodi/repository version: Krypton
- **Code location**
  - URL: https://github.com/chrisbevan/script.musicfinder
  - Revision/tag: 538d31021f0852d5978d818563eaf85d59d44f49
  - Branch: master

### Description of changes:
Music Finder is a simple script to let users move directly to the currently playing artist or album's listing from the 'now playing' music screen. I'll be using it in the Pellucid skin, but the script could easily be retooled for use by other skinners if they find it useful.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by Razzeee** [comment]
The icon seems to just be white?

**Comment by chrisbevan** [comment]
Yes, it seemed unnecessary to include a logo given the type of script. Is
it essential I supply one?

Chris.

**Comment by Razzeee** [comment]
Well you can omit it and it will fall back to the default one.

**Comment by ronie** [comment]
a few remarks about your addon.xml file:

- this is not a plugin, so please don't use the plugin extension point :-)
- there's no need to depend on xbmc.json / xbmc.addon
- please depend on the correct python version for krypton: http://kodi.wiki/view/Addon.xml#Dependency_versions

**Comment by chrisbevan** [comment]
Thanks both, fixed:
Revision: 655848f2624c855a4b127cb76996d00a3812b0f7 
Branch: Master

**Comment by ronie** [comment]
merged https://github.com/xbmc/repo-scripts/issues/460
