### ISSUE TITLE
[service.subtitles.titlovi] v1.1.2

### ISSUE THREAD

**Issue by mikimac** [xbmc/repo-scripts#457]
### Add-on details:
- **General**
  - Add-on name: Titlovi.com
  - Add-on ID: service.subtitles.titlovi
  - Version number: 1.1.2
  - Kodi/repository version: Gotham
- **Code location**
  - URL: https://github.com/mikimac/service.subtitles.titlovi
  - Revision/tag: e2c4abf
  - Branch: master

### Description of changes:
- Update new code and search engine because of removed api search on titlovi.com
- Fixed automatic search on tv shows

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Razzeee** [comment]
https://github.com/mikimac/service.subtitles.titlovi/blob/master/addon.xml
Still seems to be compatible to frodo, as there is already a version of this in the repo I would suggest updating the gotham version instead of targeting jarvis and krypton.

**Comment by mikimac** [comment]
Thanks for your advice. You are correct, this update is compatible with frodo. 
This is update for the old version because of changes in titlovi com API. 
Old verson of this addon that is in the repo is v1.0.8

**Comment by Razzeee** [comment]
I also took the liberty to grab the lastest version f63aabfb6a7b6705fef34673139b13ce8e873911 instead of the one mentioned here. Due to just changelog changes.

**Comment by mikimac** [comment]
Yes that is the lastest version, with all changes.

**Comment by ronie** [comment]
merged: https://github.com/xbmc/repo-scripts/pull/461
