### ISSUE TITLE
[Update] script.tag-generator

### ISSUE THREAD

**Issue by wellspokenman** [xbmc/repo-scripts#478]
### Add-on details:

- **General**
  - Add-on name: Tag Generator
  - Add-on ID: script.tag-generator
  - Version number: 0.5
  - Kodi/repository version:
https://github.com/wellspokenman/tag-generator/commit/881409737f525f9c1a3cbcae5e330692aa505440
- **Code location**
  - URL:https://github.com/wellspokenman/tag-generator
  - Revision/tag: 8814097
  - Branch: master

### Description of changes:
Added support for Trakt watchlists, corrected some URLs. Dependencies for this functionality included under lib. Tested on ubuntu and windows, Kodi 16 and 17. 

### Checklist:

- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Razzeee** [comment]
The news in your addon.xml should only include the latest change

**Comment by wellspokenman** [comment]
The wiki was not explicit about that. See https://github.com/wellspokenman/tag-generator/commit/522e01a2891e0b7c83993f399ccb1bdd3c29c343

**Comment by Razzeee** [comment]
@wellspokenman thanks for letting me know, I just updated the wiki

**Comment by wellspokenman** [comment]
Thank you. I've updated the issue with the new commit presenting only the most recent changes in <news>.

**Comment by enen92** [comment]
can you please change the name of your PR to the default style? [script.x] version

**Comment by Razzeee** [comment]
Can you also change "en" here to "en_GB"
https://github.com/wellspokenman/tag-generator/blob/master/addon.xml#L14-L15

**Comment by wellspokenman** [comment]
Done. Updated issue with new commit.

**Comment by wellspokenman** [comment]
Also, if there's any reading on how to do a proper pull request, I'd appreciate being pointed in the right direction.

**Comment by Razzeee** [comment]
Any specific part you're struggling with? Which operation system are you using

**Comment by wellspokenman** [comment]
I use windows and linux to interact with the git command line, but I only ever use add/commit/checkout/status/log. I _assume_ that a pull request is a request to pull my code into the master Kodi branch, that offers line by line review/compare for the approver? But I am both unsure of where to find my addon inside the main repo, and unable to use the git website to choose the tag-gen repo to compare against this (seems to be made for comparing different branches within the same repo).

**Comment by Razzeee** [comment]
![image](https://cloud.githubusercontent.com/assets/5943908/24951827/f2889c74-1f75-11e7-985b-4c8eeadf031d.png)
Click on `fork`, then grab the url to your repo should be https://github.com/YOURNAME/repo-scripts.git

Clone it to your local machine (I think you know how), switch to the target branch for your addon, in this case probably `krypton` as I think this is a new submission. Then just copy a version of your addon into the folder your in. You want delete the `.git` folder of the addon folder you just copied just in case, then just add everything and commit it with the message `[script.tag-generator] 0.0.5`. Then you want to push to a new branch with some name you choose, like `add-tag-generator` for example.

If you've done all that, just come back to the repo here: https://github.com/xbmc/repo-scripts and there should be a very obvious button to create a pull request. Click it, then you'll get a window where you choose the base and the head. The base needs to be xbmc/krypton the head YOURGITHUBNAME/add-tag-generator
Fill in the data and submit it.

**Comment by wellspokenman** [comment]
hmmm. Tried a couple of times without luck. I clone, checkout krypton, copy my files, add, commit, then try to push my commit to a new branch, but that's where it breaks. 
x@x:~/Downloads/kodi-fork$ git push -u origin "add-tag-generator"
error: src refspec add-tag-generator does not match any.

**Comment by Razzeee** [comment]
the `origin` remote is configured to be this? https://github.com/wellspokenman/repo-scripts

**Comment by wellspokenman** [comment]
that did it - thanks very much for teaching me. Added a new remote, checked out new branch and pushed to the new remote. Both firefox and chrome have a panic attack (30% CPU + 4gb ram) when I try to push that new compare button, but I guess I can just leave this issue open and do a PR when I release 0.6.

**Comment by wellspokenman** [comment]
that did it - thanks very much for teaching me. Added a new remote, checked out new branch and pushed to the new remote. Both firefox and chrome have a panic attack (30% CPU + 4gb ram) when I try to push that new compare button, but I guess I can just leave this issue open and do a PR when I release 0.6.

**Comment by wellspokenman** [comment]
Just checking: this is in the queue, right? I know I confused matters by asking about how to do a PR, but I assumed it was still allowed to submit this version via an issue.

**Comment by Razzeee** [comment]
Oh, sorry, I thought you would be creating a PR by yourself :)
I will prepare something in the next days.

**Comment by Razzeee** [comment]
Would be cool, if you could:

- Remove all *.pyo files from your repo
- Reference dependencies in addon.xml instead of inlining the whole code. Should work for six, requests and simplejson (you already do it for simplejson so you actually get that part two times https://github.com/wellspokenman/tag-generator/blob/master/addon.xml#L8)

Just add:
    <import addon="script.module.requests" version="2.12.4"/>
    <import addon="script.module.six" version="1.9.0"/>

The others haven't been moved to modules yet, unfortunatly.

**Comment by wellspokenman** [comment]
Sorry for the delay, real life did it's thing for a while there. New commit 1be8876 submitted. https://github.com/wellspokenman/tag-generator/commit/1be887623f29b99691cc66e79e4bf0ccb5dbb3f1

**Comment by wellspokenman** [comment]
Any progress here?

**Comment by wellspokenman** [comment]
Did you know that today is our three month anniversary? Seems like only yesterday.

**Comment by Razzeee** [comment]
Seems like you still have simplejson and requests included in your addon?
These shouldn't be needed due to the dependencies you set in the previous commit. https://github.com/wellspokenman/tag-generator/tree/master/resources/lib

**Comment by wellspokenman** [comment]
Those modules are used by Trakt, they need to be available outside of Kodi.
