### ISSUE TITLE
[script.module.dropbox2]  0.0.1

### ISSUE THREAD

**Issue by OptimusGREEN** [xbmc/repo-scripts#619]
### Add-on details:

- **General**
  - Add-on name: Dropbox Python API v2
  - Add-on ID: script.module.dropbox2
  - Version number: 0.0.1
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/OptimusGREEN/script.module.dropbox2
  - Revision/tag: 323cd56
  - Branch: master

### Description of changes:

Official Dropbox API v2 unofficially packaged for Kodi

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by OptimusGREEN** [comment]
Hopefully this type of submission will be more successful that the pull requests i tried.

**Comment by Razzeee** [comment]
Will you also send something that uses this module? Otherwise we won't be able to include it due to our addon rules. See http://kodi.wiki/view/Add-on_rules#Repository_Submission_Guidelines_-_Please_Read_Before_Submitting_Your_Addon

**Comment by SchapplM** [comment]
I am currently working on [refactoring the addon service.watchedlist](https://github.com/SchapplM/xbmc-addon-service-watchedlist/issues/30) which use script.module.dropbox (with Dropbox API v1).
Since API v1 is deprecated now, I intend to use this addon (script.module.dropbox2). We should merge my pull request (To be done) and this one together in a few days.

One other thing: Please delete the [zip file script.module.dropbox2.zip](https://github.com/OptimusGREEN/script.module.dropbox2/blob/master/script.module.dropbox2.zip) from the repo. You can generate a zip file with the download function of github.

**Comment by OptimusGREEN** [comment]
yeah sounds good as my add-on isn't ready for public release. zip removed.

**Comment by SchapplM** [comment]
As discussed [here](https://github.com/micahg/script.module.dropbox/issues/5#issuecomment-340259340), @micahg and I intend to upgrade the existing [script.module.dropbox](https://github.com/micahg/script.module.dropbox) to the new API. So we could close/reject this issue/pull request.

**Comment by micahg** [comment]
@OptimusGREEN were you able to get around the issue with the requests module? If you have a workaround I'd be interested in including it -- not sure how long the requests/urllib3 rework will take.

**Comment by OptimusGREEN** [comment]
Sorry, I have been both busy and sick this week which isn't a great combo.

I am not aware of the issue you mention, the only issue I came across was with the stone validator causing a problem with large uploads. I managed to fix it with a try except.

I have only used this module with my add-on tho and it maybe doesn't try to utilize the function with the issue.
