### ISSUE TITLE
[NEW] script.module.pymysql

### ISSUE THREAD

**Issue by smitchell6879** [xbmc/repo-scripts#818]
### Add-on details:
- **General**
  - Add-on name: PyMySQL
  - Add-on ID: script.module.pymysql
  - Version number: 0.8.0
  - Kodi/repository version: 17 & 18
- **Code location**
  - URL: https://github.com/smitchell6879/script.module.pymysql/releases/tag/0.8.0
  - Revision/tag:  0.8.0
  - Branch: master
### Description of changes:
It is a simple MySQL connector for python. 

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
### Note:
I am submitting this a split for my plugin, plugin.video.specialfeatures. This is required for my plugin to work properly.

**Comment by Rechi** [comment]
@smitchell6879 can you create a Pull Request against the krypton branch of this repo yourself?

Some info can be found at https://kodi.wiki/view/Submitting_Add-ons#Pull_requests

**Comment by smitchell6879** [comment]
I think I figured it out.

**Comment by Lunatixz** [comment]
Moved to PR: https://github.com/xbmc/repo-scripts/pull/819
