### ISSUE TITLE
[Update] service.subtitles.argenteam

### ISSUE THREAD

**Issue by fedux** [xbmc/repo-scripts#937]
### Add-on details:

- **General**
  - Add-on name: Argenteam.net
  - Add-on ID: service.subtitles.argenteam
  - Version number: 0.9.5
  - Kodi/repository version: Isengard

- **Code location**
  - URL: https://github.com/estemendoza/service.subtitles.argenteam
  - Revision/tag: 8b05653
  - Branch: master

**Comment by fedux** [comment]
CC @estemendoza

**Comment by Rechi** [comment]
@estemendoza or @fedux can you open a PR? It's easier for us.

**Comment by fedux** [comment]
Sure, I can do that.
