### ISSUE TITLE
Remove service.nextup.notification from Leia onwards

### ISSUE THREAD

**Issue by im85288** [xbmc/repo-scripts#961]
Remove service.nextup.notification from Leia onwards

Hello, I have replaced this addon with the new upnext addon (in leia repo) and would like to remove this addon from the Leia repo onwards.

Can someone let me know what needs to be done to achieve this?

Thanks 

### Add-on details:

- **General**
  - Add-on name: 
  - Add-on ID:
  - Version number:
  - Kodi/repository version:

- **Code location**
  - URL:
  - Revision/tag: 
  - Branch:

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Rechi** [comment]
Submit a dummy service.nextup.notification add-on marked as broken with a higher version to the leia branch.

**Comment by im85288** [comment]
Cool thanks
