### ISSUE TITLE
[Broken] - Add-on:1ting (albums)

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-scripts#967]
**[Broken] - Add-on:1ting (albums)**

### Add-on details:
- **General**
  - Add-on name:  **1ting (albums)**
  - Add-on ID: **1ting (albums)**
  - Version number: **unknown**
  - Kodi/repository version: **Leia**
  - Author: **Taxigps**

- **Code location**
  - URL: **Unknown**
                **https://kodi.wiki/view/Add-on:1ting_(albums)**
  - Revision/tag: 
  - Branch:

### Description of changes:
Nil Changes.
**N/A**

### Checklist:
**N/A**

**Comment by Rechi** [comment]
This add-on was only in the frodo repo, wiki site was a leftover.
